export const LOAD_REVIEWS = 'LOAD_REVIEWS';
export const REMOVE_REVIEW = 'REMOVE_REVIEW';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';